### ISSUE TITLE
Installation doesn't fail if docker isn't installed

### ISSUE THREAD

**Issue by RichardoC** [The-Art-of-Hacking/h4cker#101]
While attempting to install websploit on an arm64 machine which didn't have docker installed, the install succeeds and tells me a number of container IPs, despite no containers running. I was expecting the install to fail before that

Below are the full installation logs which hopefully will help.

[logs.txt](https://github.com/The-Art-of-Hacking/h4cker/files/10734350/logs.txt)

**Comment by santosomar** [comment]
It looks like the script was not recognizing the arm64 architecture. 
```
OK
deb [arch=amd64] https://download.docker.com/linux/debian buster stable
Hit:1 https://download.docker.com/linux/debian buster InRelease
Hit:2 http://kali.download/kali kali-rolling InRelease
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  docker-ce-cli:amd64
```

I am using the same procedure in: https://get.docker.com

I will investigate and troubleshoot further on an M1/M2 system.

**Comment by santosomar** [comment]
Several of us have tried to port everything to the M1/M2 systems and it is extremely frustrating and hard. I will add a note that WebSploit will not run well in an Apple (MAC) M1/M2 system.

**Comment by RichardoC** [comment]
@santosomar Where is the source for <https://websploit.org/install.sh> ? I'd like to update it to fail on attempted installation on non amd64 systems to prevent others having this issue

**Comment by Egor4ik888** [comment]
[``]([url](
/))

**Comment by Egor4ik888** [comment]
###

**Comment by fddemora** [comment]
I believe my issue is coming from line 51: 
`sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

Thus docker won't run or install as expected due to this URL: 
`https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-aarch64`

**Comment by fddemora** [comment]
Problem extends to ARM architecture as images pulled from the web are for x86-64 architecture. Basically, don't use ARM for this project.
