### ISSUE TITLE
unable to run websploit labs.

### ISSUE THREAD

**Issue by AVI-SHUKLA1110** [The-Art-of-Hacking/h4cker#102]
hi everyone! i recently installed the websploit labs on my parrot os , but i am unable to find how to see it on my terminal and have no idea on how to use it,...
ANY HELP WOULD BE HIGHLY APPRECIATED..
-avi_shukla@outlook.com

**Comment by santosomar** [comment]
You do not "run" WebSploit Labs. WebSploit is a series of resources and intentionally vulnerable applications running in containers. The instructions of setup are in the website (https://websploit.org/) as well as the list of intentionally vulnerable containers. You can use the `containers` command to see the running containers and other information. For example:
```
┌──(omar㉿websploit)-[~]
└─$ sudo containers
[sudo] password for omar:

WebSploit
by Omar Santos @santosomar
-------------------------------------
Internal Hacking Network: 10.6.6.0/24
Your bridge networks:
br-e0abc2ca5a9a  UP             10.6.6.1/24 fe80::42:16ff:fea7:e7ad/64

The following are the WebSploit vulnerable containers and associated IP addresses.
+------------------------+------------+
|     Container          | IP Address |
+------------------------+------------+
| webgoat                |  10.6.6.11 |
| juice-shop             |  10.6.6.12 |
| dvwa                   |  10.6.6.13 |
| mutillidae_2           |  10.6.6.14 |
| dvna                   |  10.6.6.15 |
| hackazon               |  10.6.6.16 |
| hackme-rtov            |  10.6.6.17 |
| mayhem                 |  10.6.6.18 |
| rtv-safemode           |  10.6.6.19 |
| grayhat-mmxx           |  10.6.6.20 |
| yascon-hackme          |  10.6.6.21 |
| secretcorp-branch1     |  10.6.6.22 |
| gravemind              |  10.6.6.23 |
| dc30_01                |  10.6.6.24 |
| dc30_01                |  10.6.6.25 |
| nodegoat (manual)      |  10.6.7.2  |
| api_gateway (manual)   |  10.6.7.3  |
| etcd (for api_gateway) |  10.6.7.4  |
+------------------------+------------+
The following are the running containers with their associated ports:
NAMES                PORTS                STATUS
yascon-hackme        80/tcp               Up 5 weeks
hackme-rtov          80/tcp               Up 5 weeks
mutillidae_2         80/tcp, 3306/tcp     Up 5 weeks
dc30_01              22/tcp, 3000/tcp     Up 5 weeks
secretcorp-branch1   80/tcp               Up 5 weeks
webgoat              8080/tcp, 9090/tcp   Up 5 weeks
grayhat-mmxx         8000/tcp             Up 5 weeks
dc30_02                                   Up 5 weeks
juice-shop           3000/tcp             Up 5 weeks
gravemind                                 Up 5 weeks (healthy)
hackazon             80/tcp               Up 5 weeks
rtv-safemode         80/tcp, 3306/tcp     Up 5 weeks
dvna                                      Up 5 weeks
mayhem               22/tcp, 80/tcp       Up 5 weeks
dvwa                 80/tcp               Up 5 weeks
```

**Comment by DeepakBanger2005** [comment]
sir i deployed the lab in my kali vm as instructed on the website. but after i restarted the kali machine, it is having black screen while trying to log in.  i tried it twice, but still having the same issue. Please help me

**Comment by amritabithi** [comment]
> sir i deployed the lab in my kali vm as instructed on the website. but after i restarted the kali machine, it is having black screen while trying to log in. i tried it twice, but still having the same issue. Please help me

If you are logging in remotely:
The first thing that I would check is to make sure you do not have any old connections to it still open, including SFTP, and power cycle / restart again.

Also if there is a managed firewall on your host meaning that you can manage firewall settings through their website then make sure all of the ports that you need are open and if possible whitelist your own IP address for SSH to rule out that blocking you.

If you are next to the computer it runs on:
Boot in safe mode and look in your log files like kern.log
```
cd /var/logs/
sudo cat kern.log
```

**Comment by DeepakBanger2005** [comment]
I'm sorry, it is working properly now. The problem was in the vm storage.
I'm a newbie so, hope you would understand.
Thanks for helping BTW 😃

**Comment by amritabithi** [comment]
> I'm sorry, it is working properly now. The problem was in the vm storage. I'm a newbie so, hope you would understand. Thanks for helping BTW 😃
> […](#)
> Message ID: ***@***.***>

Awesome I am glad that you figured it out and for replying, the next person with the same issue will be grateful for the tip in checking that.

And being a newbie is good a newbie is always learning.  The only actual newbie mistake that a person can make is to believe they are an expert and that they know everything, and that is when the tragic or hilarious accidents all come from.
