### ISSUE TITLE
NodeGoat fails to start in WebSploit due to version of MongoDB being pulled

### ISSUE THREAD

**Issue by ebell451** [The-Art-of-Hacking/h4cker#115]
NodeGoat failed to start due to an issue with the MongoDB image in `NodeGoat/docker-compose.yml`. 

MongoDB container failed to start with the following error:

![image](https://user-images.githubusercontent.com/3712453/236747848-331475f3-48a7-4cb5-b021-34ab2e283c9b.png)

I was able to workaround this by modifying the tag for the MongoDB image being pulled to `mongo:4.4`.
![image](https://user-images.githubusercontent.com/3712453/236748274-a773607a-a4a9-4ec6-abb6-6ac1e2291079.png)

This is also the version of MongoDB used by the original NodeGoat from OWASP: https://github.com/OWASP/NodeGoat/blob/master/docker-compose.yml

**Comment by santosomar** [comment]
Thank you! I will troubleshoot shortly.

**Comment by santosomar** [comment]
I will remove support for NodeGoat for now. I am adding several additional containers for DEF CON this year. They will be published within the next few days. I will consider re-adding NodeGoat after DEF CON 31. However, I cannot promise that I will have the time. :-(

**Comment by santosomar** [comment]
I have updated the install script. I have also added several new containers in preparation to DEF CON 31 this year. I will document Node Goat a little better once I return from DEF CON. Thank you for your patience on this one.
