### ISSUE TITLE
Undefined names in SCOR/threat-response-api-example.py

### ISSUE THREAD

**Issue by cclauss** [The-Art-of-Hacking/h4cker#24]
[./SCOR/threat-response-api-example.py#L92-L99](../blob/master/SCOR/threat-response-api-example.py#L92-L99)

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./SCOR/threat-response-api-example.py:96:42: F821 undefined name 'text_block'
    response = TR_check_auth(TR_inspect, text_block)
                                         ^
./SCOR/threat-response-api-example.py:98:30: F821 undefined name 'TR_enrich'
    response = TR_check_auth(TR_enrich, inspect_output)
                             ^
```
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python a __NameError__ is raised which will halt/crash the script on the user.

**Comment by santosomar** [comment]
This is a generic example. It looks like this issue was opened after running `flake8`.
`flake8` is a command-line utility for enforcing style consistency across Python projects. By default it includes lint checks provided by the PyFlakes project, PEP-0008 inspired style checks provided by the PyCodeStyle project, and McCabe complexity checking provided by the McCabe project. It will also run third-party extensions if they are found and installed.
