### ISSUE TITLE
error whlie executing code in kali linux : pip install -r requirements.txt

### ISSUE THREAD

**Issue by ruthviksai03** [The-Art-of-Hacking/h4cker#32]
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/kti/python-netfilterqueue (from -r requirements.txt (line 1))
  Cloning https://github.com/kti/python-netfilterqueue to /tmp/pip-req-build-5lmtH3
  Running command git clone -q https://github.com/kti/python-netfilterqueue /tmp/pip-req-build-5lmtH3
Requirement already satisfied: pyinotify in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (0.9.6)
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (2.6.1)
Requirement already satisfied: pyasn1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (0.4.2)
Requirement already satisfied: cryptography in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (2.6.1)
Requirement already satisfied: Pillow in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (6.2.0)
Requirement already satisfied: netaddr in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7)) (0.7.19)
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 8)) (2.4.3)
Requirement already satisfied: dnslib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9)) (0.9.14)
Requirement already satisfied: Twisted in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 10)) (18.9.0)
Requirement already satisfied: lxml in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 11)) (4.4.1)
Requirement already satisfied: pefile in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (2019.4.18)
Requirement already satisfied: ipy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (0.83)
Requirement already satisfied: user_agents in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14)) (2.1)
Requirement already satisfied: pyopenssl in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 15)) (19.0.0)
Requirement already satisfied: service_identity in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 16)) (18.1.0)
Requirement already satisfied: configobj in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17)) (5.0.6)
Requirement already satisfied: Flask in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 18)) (1.1.1)
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 19)) (1.16.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 20)) (4.8.0)
Requirement already satisfied: capstone in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 21)) (4.0.2)
Requirement already satisfied: python-magic in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 22)) (0.4.16)
Requirement already satisfied: msgpack-python in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 23)) (0.5.6)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 24)) (2.21.0)
Collecting pypcap
  Using cached pypcap-1.2.3.tar.gz (136 kB)
Requirement already satisfied: chardet in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 26)) (3.0.4)
Requirement already satisfied: ua-parser>=0.9.0 in /usr/local/lib/python2.7/dist-packages (from user_agents->-r requirements.txt (line 14)) (0.10.0)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/dist-packages (from service_identity->-r requirements.txt (line 16)) (1.0.17)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from configobj->-r requirements.txt (line 17)) (1.13.0)
Using legacy setup.py install for pypcap, since package 'wheel' is not installed.
Using legacy setup.py install for NetfilterQueue, since package 'wheel' is not installed.
Installing collected packages: pypcap, NetfilterQueue
    Running setup.py install for pypcap ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9Tno8n/pypcap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9Tno8n/pypcap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-H6wsGA/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/pypcap                                                                                                                                                      
         cwd: /tmp/pip-install-9Tno8n/pypcap/                                                                                                                         
    Complete output (15 lines):                                                                                                                                       
    Found pcap headers in /usr/include/pcap.h                                                                                                                         
    Found libraries in /usr/lib/x86_64-linux-gnu/libpcap.so                                                                                                           
    found pcap_get_tstamp_precision function                                                                                                                          
    found pcap_setdirection                                                                                                                                           
    found pcap_setnonblock                                                                                                                                            
    found pcap_compile_nopcap function                                                                                                                                
    running install                                                                                                                                                   
    running build                                                                                                                                                     
    running build_ext                                                                                                                                                 
    building 'pcap' extension                                                                                                                                         
    creating build                                                                                                                                                    
    creating build/temp.linux-x86_64-2.7                                                                                                                              
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-07FOaN/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_PCAP_TSTAMP_PRECISION=1 -DHAVE_PCAP_SETDIRECTION=1 -DHAVE_PCAP_SETNONBLOCK=1 -DHAVE_PCAP_COMPILE_NOPCAP=1 -I/usr/include -I/usr/include/python2.7 -c pcap.c -o build/temp.linux-x86_64-2.7/pcap.o                                                                                  
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory                                                                                               
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                                                                   
    ----------------------------------------                                                                                                                          
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9Tno8n/pypcap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9Tno8n/pypcap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-H6wsGA/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/pypcap Check the logs for full command output.

**Comment by santosomar** [comment]
Hi! Thank you for your submission. It looks like this is probably a Kali Linux dependent issue.  You can submit errors like this (depending on the Kali version) directly to the Offensive Security repo(s): https://github.com/offensive-security
