### ISSUE TITLE
Wrong buffer size?

### ISSUE THREAD

**Issue by fagcinsk** [The-Art-of-Hacking/h4cker#39]
https://github.com/The-Art-of-Hacking/h4cker/blob/49d75b8d345f497ec49f323027a8bfe9082812dd/python_ruby_and_bash/http_sniffer.py#L9

TCP max packet size is 65535

**Comment by santosomar** [comment]
Thank you so much for your finding! I will address it shortly. Yes indeed, that is a typo and the TCP max packet size is 65535.
