### ISSUE TITLE
Installing websploit.org tools in Kali 

### ISSUE THREAD

**Issue by logicito** [The-Art-of-Hacking/h4cker#85]
Apologies if this is the wrong place to ask the question, I am installing in Kali the tools from the websploit.org site (as part of an O'Reilly course), at the end of the installation I get an error with docker: "/usr/local/bin/containers: line 36: docker: command not found, if I try to start the service it says "unit: docker.service not found". Please could you guide me to the right place to get help, thank you

**Comment by santosomar** [comment]
It looks like either the actual docker package was not installed successfully or the docker service is not running.

If Docker was not installed successfully, you can use the following:

```
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' | sudo tee /etc/apt/sources.list.d/docker.list
apt update
apt remove docker docker-engine docker.io
apt install -y docker-ce
```

If Docker was installed successfully and you run into that problem, then try to start the Docker service by using the following command:
```
service docker start
````

**Comment by santosomar** [comment]
Hope that helps. I will close this issue for now. If you run into any further trouble feel free to ping me in Discord https://redteamvillage.io/discord or here.
