### ISSUE TITLE
trojan in cqtools

### ISSUE THREAD

**Issue by olsmanJr1** [The-Art-of-Hacking/h4cker#98]
http://feedproxy.google.com/~r/PentestTools/~3/jwnMIPJ7f80/cqtools-new-ultimate-windows-hacking.html that link or app has a trojan keylogger why? https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=TrojanSpy:MSIL/Keylogger.A&threatId=-2147329508 thats the description oifi t

**Comment by santosomar** [comment]
That is a series of tools that include things like keyloggers for offensive security operations.

Please see [this short presentation](https://i.blackhat.com/asia-19/Thu-March-28/bh-asia-Januszkiewicz-CQTools-New-Ultimate-Hacking-Toolkit.pdf)

Also this [whitepaper](https://i.blackhat.com/asia-19/Thu-March-28/bh-asia-Januszkiewicz-CQTools-New-Ultimate-Hacking-Toolkit-wp.pdf)

"This toolkit allows to deliver complete attacks within the infrastructure, starting with sniffing and spoofing
activities, going through information extraction, password extraction, custom shell generation, custom payload
generation, hiding code from antivirus solutions, various keyloggers and leverage this information to deliver
attacks. Some of the tools are based on discoveries that were released to the world for the first time by CQURE
Team. CQURE was the first team that did a full reverse engineering of DPAPI (Data Protection Application
Programming Interface) and prepared the first public tool that allows to monitor WSL (Windows Subsystem
for Linux) feature."

**Comment by olsmanJr1** [comment]
where is a good place to look for things like tools and guides to help me
learn more
